# Generated by Django 4.2 on 2025-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
