# Generated by Django 4.2 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_cashcategory_delete_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashcategory',
            name='details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cashcategory',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
