# Generated by Django 4.2 on 2025-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_cashbox_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
