# Generated by Django 4.2 on 2025-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_cashbox_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
