# Generated by Django 4.2 on 2025-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_cashtransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
