# Generated by Django 4.2 on 2025-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_cashtransaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
